<?php
/*
 * This call will pull only from ServicebusGetBillingInformation.
 */



include '../functions.php';

$_FAKE_json_sb_call =
    '{
        "responseCode":"1000",
            "responseObject":{
                "state":"TX",
                "typeName":"creditCardInfo",
                "country":"United States of America",
                "fullName":"toyin akinmusuru",
                "email":null,
                "customerId":null,
                "city":"*THIS IS FAKE DATA* testville",
                "postalCode":"*THIS IS FAKE DATA* 78704",
                "gatewayServiceToken":"9qmvn",
                "ccNumber":null,
                "ccCVV":null,
                "last4":"1111",
                "storeCustomerId":"803",
                "streetAddress":"*THIS IS FAKE DATA* 123 test street",
                "ccFirstName":"toyin",
                "ccLastName":"akinmusuru",
                "extendedAddress":null,
                "alpha2Country":"US",
                "ccExpDate":"04/2014",
                "ccExpMonth":"04",
                "ccExpYear":"2014",
                "ipAddress":null,
                "ccNumberMasked":"411111******1111",
                "gatewayServiceCustomerId":"9001803",
                "gatewayServiceType":"BRAINTREE",
                "name":null,
                "id":null,
                "creationTime":null,
                "modificationTime":null,
                "guid":null
            },
        "responseText":"successful"
    }';


function return_new_json($sbJson)
{
    /* at 27/02/13 is coming the following from SB for billinginfo
    {
       "responseCode":"1000",
       "responseObject":{
          "state":null,
          "typeName":"creditCardInfo",
          "country":null,
          "fullName":"null null",
          "email":null,
          "city":null,
          "postalCode":null,
          "gatewayServiceToken":null,
          "ccNumber":null,
          "ccCVV":null,
          "customerId":null,
          "last4":null,
          "storeCustomerId":null,
          "streetAddress":null,
          "ccFirstName":null,
          "ccLastName":null,
          "extendedAddress":null,
          "alpha2Country":"US",
          "ccExpDate":"null/null",
          "ccExpMonth":null,
          "ccExpYear":null,
          "ipAddress":null,
          "ccNumberMasked":null,
          "gatewayServiceCustomerId":null,
          "gatewayServiceType":null,
          "name":null,
          "id":null,
          "creationTime":null,
          "guid":null,
          "modificationTime":null
       },
       "responseText":"successful"
    }
    */
    $countries = Array(
        Array('value' =>"AF", "label" => "Afghanistan"),
        Array('value' =>"AL", "label" => "Albania"),
        Array('value' =>"DZ", "label" => "Algeria"),
        Array('value' =>"AS", "label" => "American Samoa"),
        Array('value' =>"AD", "label" => "Andorra"),
        Array('value' =>"AO", "label" => "Angola"),
        Array('value' =>"AI", "label" => "Anguilla"),
        Array('value' =>"AQ", "label" => "Antarctica"),
        Array('value' =>"AG", "label" => "Antigua and Barbuda"),
        Array('value' =>"AR", "label" => "Argentina"),
        Array('value' =>"AM", "label" => "Armenia"),
        Array('value' =>"AW", "label" => "Aruba"),
        Array('value' =>"AU", "label" => "Australia"),
        Array('value' =>"AT", "label" => "Austria"),
        Array('value' =>"AZ", "label" => "Azerbaijan"),
        Array('value' =>"BS", "label" => "Bahamas"),
        Array('value' =>"BH", "label" => "Bahrain"),
        Array('value' =>"BD", "label" => "Bangladesh"),
        Array('value' =>"BB", "label" => "Barbados"),
        Array('value' =>"BY", "label" => "Belarus"),
        Array('value' =>"BE", "label" => "Belgium"),
        Array('value' =>"BZ", "label" => "Belize"),
        Array('value' =>"BJ", "label" => "Benin"),
        Array('value' =>"BM", "label" => "Bermuda"),
        Array('value' =>"BT", "label" => "Bhutan"),
        Array('value' =>"BO", "label" => "Bolivia"),
        Array('value' =>"BA", "label" => "Bosnia and Herzegovina"),
        Array('value' =>"BW", "label" => "Botswana"),
        Array('value' =>"BV", "label" => "Bouvet Island"),
        Array('value' =>"BR", "label" => "Brazil"),
        Array('value' =>"IO", "label" => "British Indian Ocean Territory"),
        Array('value' =>"VG", "label" => "British Virgin Islands"),
        Array('value' =>"BN", "label" => "Brunei"),
        Array('value' =>"BG", "label" => "Bulgaria"),
        Array('value' =>"BF", "label" => "Burkina Faso"),
        Array('value' =>"BI", "label" => "Burundi"),
        Array('value' =>"KH", "label" => "Cambodia"),
        Array('value' =>"CM", "label" => "Cameroon"),
        Array('value' =>"CA", "label" => "Canada"),
        Array('value' =>"CV", "label" => "Cape Verde"),
        Array('value' =>"KY", "label" => "Cayman Islands"),
        Array('value' =>"CF", "label" => "Central African Republic"),
        Array('value' =>"TD", "label" => "Chad"),
        Array('value' =>"CL", "label" => "Chile"),
        Array('value' =>"CN", "label" => "China"),
        Array('value' =>"CX", "label" => "Christmas Island"),
        Array('value' =>"CC", "label" => "Cocos [Keeling] Islands"),
        Array('value' =>"CO", "label" => "Colombia"),
        Array('value' =>"KM", "label" => "Comoros"),
        Array('value' =>"CG", "label" => "Congo - Brazzaville"),
        Array('value' =>"CD", "label" => "Congo - Kinshasa"),
        Array('value' =>"CK", "label" => "Cook Islands"),
        Array('value' =>"CR", "label" => "Costa Rica"),
        Array('value' =>"HR", "label" => "Croatia"),
        Array('value' =>"CU", "label" => "Cuba"),
        Array('value' =>"CY", "label" => "Cyprus"),
        Array('value' =>"CZ", "label" => "Czech Republic"),
        Array('value' =>"CI", "label" => "Côte d’Ivoire"),
        Array('value' =>"DK", "label" => "Denmark"),
        Array('value' =>"DJ", "label" => "Djibouti"),
        Array('value' =>"DM", "label" => "Dominica"),
        Array('value' =>"DO", "label" => "Dominican Republic"),
        Array('value' =>"EC", "label" => "Ecuador"),
        Array('value' =>"EG", "label" => "Egypt"),
        Array('value' =>"SV", "label" => "El Salvador"),
        Array('value' =>"GQ", "label" => "Equatorial Guinea"),
        Array('value' =>"ER", "label" => "Eritrea"),
        Array('value' =>"EE", "label" => "Estonia"),
        Array('value' =>"ET", "label" => "Ethiopia"),
        Array('value' =>"FK", "label" => "Falkland Islands"),
        Array('value' =>"FO", "label" => "Faroe Islands"),
        Array('value' =>"FJ", "label" => "Fiji"),
        Array('value' =>"FI", "label" => "Finland"),
        Array('value' =>"FR", "label" => "France"),
        Array('value' =>"GF", "label" => "French Guiana"),
        Array('value' =>"PF", "label" => "French Polynesia"),
        Array('value' =>"TF", "label" => "French Southern Territories"),
        Array('value' =>"GA", "label" => "Gabon"),
        Array('value' =>"GM", "label" => "Gambia"),
        Array('value' =>"GE", "label" => "Georgia"),
        Array('value' =>"DE", "label" => "Germany"),
        Array('value' =>"GH", "label" => "Ghana"),
        Array('value' =>"GI", "label" => "Gibraltar"),
        Array('value' =>"GR", "label" => "Greece"),
        Array('value' =>"GL", "label" => "Greenland"),
        Array('value' =>"GD", "label" => "Grenada"),
        Array('value' =>"GP", "label" => "Guadeloupe"),
        Array('value' =>"GU", "label" => "Guam"),
        Array('value' =>"GT", "label" => "Guatemala"),
        Array('value' =>"GG", "label" => "Guernsey"),
        Array('value' =>"GN", "label" => "Guinea"),
        Array('value' =>"GW", "label" => "Guinea-Bissau"),
        Array('value' =>"GY", "label" => "Guyana"),
        Array('value' =>"HT", "label" => "Haiti"),
        Array('value' =>"HM", "label" => "Heard Island and McDonald Islands"),
        Array('value' =>"HN", "label" => "Honduras"),
        Array('value' =>"HK", "label" => "Hong Kong SAR China"),
        Array('value' =>"HU", "label" => "Hungary"),
        Array('value' =>"IS", "label" => "Iceland"),
        Array('value' =>"IN", "label" => "India"),
        Array('value' =>"ID", "label" => "Indonesia"),
        Array('value' =>"IR", "label" => "Iran"),
        Array('value' =>"IQ", "label" => "Iraq"),
        Array('value' =>"IE", "label" => "Ireland"),
        Array('value' =>"IM", "label" => "Isle of Man"),
        Array('value' =>"IL", "label" => "Israel"),
        Array('value' =>"IT", "label" => "Italy"),
        Array('value' =>"JM", "label" => "Jamaica"),
        Array('value' =>"JP", "label" => "Japan"),
        Array('value' =>"JE", "label" => "Jersey"),
        Array('value' =>"JO", "label" => "Jordan"),
        Array('value' =>"KZ", "label" => "Kazakhstan"),
        Array('value' =>"KE", "label" => "Kenya"),
        Array('value' =>"KI", "label" => "Kiribati"),
        Array('value' =>"KW", "label" => "Kuwait"),
        Array('value' =>"KG", "label" => "Kyrgyzstan"),
        Array('value' =>"LA", "label" => "Laos"),
        Array('value' =>"LV", "label" => "Latvia"),
        Array('value' =>"LB", "label" => "Lebanon"),
        Array('value' =>"LS", "label" => "Lesotho"),
        Array('value' =>"LR", "label" => "Liberia"),
        Array('value' =>"LY", "label" => "Libya"),
        Array('value' =>"LI", "label" => "Liechtenstein"),
        Array('value' =>"LT", "label" => "Lithuania"),
        Array('value' =>"LU", "label" => "Luxembourg"),
        Array('value' =>"MO", "label" => "Macau SAR China"),
        Array('value' =>"MK", "label" => "Macedonia"),
        Array('value' =>"MG", "label" => "Madagascar"),
        Array('value' =>"MW", "label" => "Malawi"),
        Array('value' =>"MY", "label" => "Malaysia"),
        Array('value' =>"MV", "label" => "Maldives"),
        Array('value' =>"ML", "label" => "Mali"),
        Array('value' =>"MT", "label" => "Malta"),
        Array('value' =>"MH", "label" => "Marshall Islands"),
        Array('value' =>"MQ", "label" => "Martinique"),
        Array('value' =>"MR", "label" => "Mauritania"),
        Array('value' =>"MU", "label" => "Mauritius"),
        Array('value' =>"YT", "label" => "Mayotte"),
        Array('value' =>"MX", "label" => "Mexico"),
        Array('value' =>"FM", "label" => "Micronesia"),
        Array('value' =>"MD", "label" => "Moldova"),
        Array('value' =>"MC", "label" => "Monaco"),
        Array('value' =>"MN", "label" => "Mongolia"),
        Array('value' =>"ME", "label" => "Montenegro"),
        Array('value' =>"MS", "label" => "Montserrat"),
        Array('value' =>"MA", "label" => "Morocco"),
        Array('value' =>"MZ", "label" => "Mozambique"),
        Array('value' =>"MM", "label" => "Myanmar [Burma]"),
        Array('value' =>"NA", "label" => "Namibia"),
        Array('value' =>"NR", "label" => "Nauru"),
        Array('value' =>"NP", "label" => "Nepal"),
        Array('value' =>"NL", "label" => "Netherlands"),
        Array('value' =>"AN", "label" => "Netherlands Antilles"),
        Array('value' =>"NC", "label" => "New Caledonia"),
        Array('value' =>"NZ", "label" => "New Zealand"),
        Array('value' =>"NI", "label" => "Nicaragua"),
        Array('value' =>"NE", "label" => "Niger"),
        Array('value' =>"NG", "label" => "Nigeria"),
        Array('value' =>"NU", "label" => "Niue"),
        Array('value' =>"NF", "label" => "Norfolk Island"),
        Array('value' =>"KP", "label" => "North Korea"),
        Array('value' =>"MP", "label" => "Northern Mariana Islands"),
        Array('value' =>"NO", "label" => "Norway"),
        Array('value' =>"OM", "label" => "Oman"),
        Array('value' =>"PK", "label" => "Pakistan"),
        Array('value' =>"PW", "label" => "Palau"),
        Array('value' =>"PS", "label" => "Palestinian Territories"),
        Array('value' =>"PA", "label" => "Panama"),
        Array('value' =>"PG", "label" => "Papua New Guinea"),
        Array('value' =>"PY", "label" => "Paraguay"),
        Array('value' =>"PE", "label" => "Peru"),
        Array('value' =>"PH", "label" => "Philippines"),
        Array('value' =>"PN", "label" => "Pitcairn Islands"),
        Array('value' =>"PL", "label" => "Poland"),
        Array('value' =>"PT", "label" => "Portugal"),
        Array('value' =>"PR", "label" => "Puerto Rico"),
        Array('value' =>"QA", "label" => "Qatar"),
        Array('value' =>"RO", "label" => "Romania"),
        Array('value' =>"RU", "label" => "Russia"),
        Array('value' =>"RW", "label" => "Rwanda"),
        Array('value' =>"RE", "label" => "Réunion"),
        Array('value' =>"BL", "label" => "Saint Barthélemy"),
        Array('value' =>"SH", "label" => "Saint Helena"),
        Array('value' =>"KN", "label" => "Saint Kitts and Nevis"),
        Array('value' =>"LC", "label" => "Saint Lucia"),
        Array('value' =>"MF", "label" => "Saint Martin"),
        Array('value' =>"PM", "label" => "Saint Pierre and Miquelon"),
        Array('value' =>"VC", "label" => "Saint Vincent and the Grenadines"),
        Array('value' =>"WS", "label" => "Samoa"),
        Array('value' =>"SM", "label" => "San Marino"),
        Array('value' =>"SA", "label" => "Saudi Arabia"),
        Array('value' =>"SN", "label" => "Senegal"),
        Array('value' =>"RS", "label" => "Serbia"),
        Array('value' =>"SC", "label" => "Seychelles"),
        Array('value' =>"SL", "label" => "Sierra Leone"),
        Array('value' =>"SG", "label" => "Singapore"),
        Array('value' =>"SK", "label" => "Slovakia"),
        Array('value' =>"SI", "label" => "Slovenia"),
        Array('value' =>"SB", "label" => "Solomon Islands"),
        Array('value' =>"SO", "label" => "Somalia"),
        Array('value' =>"ZA", "label" => "South Africa"),
        Array('value' =>"GS", "label" => "South Georgia and the South Sandwich Islands"),
        Array('value' =>"KR", "label" => "South Korea"),
        Array('value' =>"ES", "label" => "Spain"),
        Array('value' =>"LK", "label" => "Sri Lanka"),
        Array('value' =>"SD", "label" => "Sudan"),
        Array('value' =>"SR", "label" => "Suriname"),
        Array('value' =>"SJ", "label" => "Svalbard and Jan Mayen"),
        Array('value' =>"SZ", "label" => "Swaziland"),
        Array('value' =>"SE", "label" => "Sweden"),
        Array('value' =>"CH", "label" => "Switzerland"),
        Array('value' =>"SY", "label" => "Syria"),
        Array('value' =>"ST", "label" => "São Tomé and Príncipe"),
        Array('value' =>"TW", "label" => "Taiwan"),
        Array('value' =>"TJ", "label" => "Tajikistan"),
        Array('value' =>"TZ", "label" => "Tanzania"),
        Array('value' =>"TH", "label" => "Thailand"),
        Array('value' =>"TL", "label" => "Timor-Leste"),
        Array('value' =>"TG", "label" => "Togo"),
        Array('value' =>"TK", "label" => "Tokelau"),
        Array('value' =>"TO", "label" => "Tonga"),
        Array('value' =>"TT", "label" => "Trinidad and Tobago"),
        Array('value' =>"TN", "label" => "Tunisia"),
        Array('value' =>"TR", "label" => "Turkey"),
        Array('value' =>"TM", "label" => "Turkmenistan"),
        Array('value' =>"TC", "label" => "Turks and Caicos Islands"),
        Array('value' =>"TV", "label" => "Tuvalu"),
        Array('value' =>"UM", "label" => "U.S. Minor Outlying Islands"),
        Array('value' =>"VI", "label" => "U.S. Virgin Islands"),
        Array('value' =>"UG", "label" => "Uganda"),
        Array('value' =>"UA", "label" => "Ukraine"),
        Array('value' =>"AE", "label" => "United Arab Emirates"),
        Array('value' =>"GB", "label" => "United Kingdom"),
        Array('value' =>"US", "label" => "United States"),
        Array('value' =>"UY", "label" => "Uruguay"),
        Array('value' =>"UZ", "label" => "Uzbekistan"),
        Array('value' =>"VU", "label" => "Vanuatu"),
        Array('value' =>"VA", "label" => "Vatican City"),
        Array('value' =>"VE", "label" => "Venezuela"),
        Array('value' =>"VN", "label" => "Vietnam"),
        Array('value' =>"WF", "label" => "Wallis and Futuna"),
        Array('value' =>"EH", "label" => "Western Sahara"),
        Array('value' =>"YE", "label" => "Yemen"),
        Array('value' =>"ZM", "label" => "Zambia"),
        Array('value' =>"ZW", "label" => "Zimbabwe"),
        Array('value' =>"AX", "label" => "Åland Islands")
    );

    $states = Array(
        Array('value' =>"AL", "label" => "Alabama"),
        Array('value' =>"AK", "label" => "Alaska"),
        Array('value' =>"AS", "label" => "American Samoa"),
        Array('value' =>"AZ", "label" => "Arizona"),
        Array('value' =>"AR", "label" => "Arkansas"),
        Array('value' =>"AF", "label" => "Armed Forces Africa"),
        Array('value' =>"AA", "label" => "Armed Forces Americas"),
        Array('value' =>"AC", "label" => "Armed Forces Canada"),
        Array('value' =>"AE", "label" => "Armed Forces Europe"),
        Array('value' =>"AM", "label" => "Armed Forces Middle East"),
        Array('value' =>"AP", "label" => "Armed Forces Pacific"),
        Array('value' =>"CA", "label" => "California"),
        Array('value' =>"CO", "label" => "Colorado"),
        Array('value' =>"CT", "label" => "Connecticut"),
        Array('value' =>"DE", "label" => "Delaware"),
        Array('value' =>"DC", "label" => "District of Columbia"),
        Array('value' =>"FM", "label" => "Federated States Of Micronesia"),
        Array('value' =>"FL", "label" => "Florida"),
        Array('value' =>"GA", "label" => "Georgia"),
        Array('value' =>"GU", "label" => "Guam"),
        Array('value' =>"HI", "label" => "Hawaii"),
        Array('value' =>"ID", "label" => "Idaho"),
        Array('value' =>"IL", "label" => "Illinois"),
        Array('value' =>"IN", "label" => "Indiana"),
        Array('value' =>"IA", "label" => "Iowa"),
        Array('value' =>"KS", "label" => "Kansas"),
        Array('value' =>"KY", "label" => "Kentucky"),
        Array('value' =>"LA", "label" => "Louisiana"),
        Array('value' =>"ME", "label" => "Maine"),
        Array('value' =>"MH", "label" => "Marshall Islands"),
        Array('value' =>"MD", "label" => "Maryland"),
        Array('value' =>"MA", "label" => "Massachusetts"),
        Array('value' =>"MI", "label" => "Michigan"),
        Array('value' =>"MN", "label" => "Minnesota"),
        Array('value' =>"MS", "label" => "Mississippi"),
        Array('value' =>"MO", "label" => "Missouri"),
        Array('value' =>"MT", "label" => "Montana"),
        Array('value' =>"NE", "label" => "Nebraska"),
        Array('value' =>"NV", "label" => "Nevada"),
        Array('value' =>"NH", "label" => "New Hampshire"),
        Array('value' =>"NJ", "label" => "New Jersey"),
        Array('value' =>"NM", "label" => "New Mexico"),
        Array('value' =>"NY", "label" => "New York"),
        Array('value' =>"NC", "label" => "North Carolina"),
        Array('value' =>"ND", "label" => "North Dakota"),
        Array('value' =>"MP", "label" => "Northern Mariana Island"),
        Array('value' =>"OH", "label" => "Ohio"),
        Array('value' =>"OK", "label" => "Oklahoma"),
        Array('value' =>"OR", "label" => "Oregon"),
        Array('value' =>"PW", "label" => "Palau"),
        Array('value' =>"PA", "label" => "Pennsylvania"),
        Array('value' =>"PR", "label" => "Puerto Rico"),
        Array('value' =>"RI", "label" => "Rhode Island"),
        Array('value' =>"SC", "label" => "South Carolina"),
        Array('value' =>"SD", "label" => "South Dakota"),
        Array('value' =>"TN", "label" => "Tennessee"),
        Array('value' =>"TX", "label" => "Texas"),
        Array('value' =>"UT", "label" => "Utah"),
        Array('value' =>"VT", "label" => "Vermont"),
        Array('value' =>"VI", "label" => "Virgin Islands"),
        Array('value' =>"VA", "label" => "Virginia"),
        Array('value' =>"WA", "label" => "Washington"),
        Array('value' =>"WV", "label" => "West Virginia"),
        Array('value' =>"WI", "label" => "Wisconsin"),
        Array('value' =>"WY", "label" => "Wyoming"));

    list($month,$year) = explode('/', $sbJson['responseObject']['ccExpDate']);

    $cc_exp_month_selected=$month;//$sbJson['responseObject']['ccExpMonth'];//change for '05' to test
    $cc_exp_year_selected= $year;//$sbJson['responseObject']['ccExpYear'];//put a number for test is:2016
    $increment_year=10;
    $response = Array(
        'billingInformation' => Array(
            'Address'       => $sbJson['responseObject']['streetAddress'],
            'City'          => $sbJson['responseObject']['city'],
            'Zip'           => $sbJson['responseObject']['postalCode'],
            'CreditCard'   => $sbJson['responseObject']['ccNumberMasked'],
            'CVV'           => '***',//$sbJson['responseObject']['ccCVV'],
            'ccExpMonth'=> $cc_exp_month_selected,
            'ccExpYear'=> $cc_exp_year_selected,
            'ExpirationMonth'    => setmonth($cc_exp_month_selected),
            'ExpirationYear'    => setyear($increment_year,$cc_exp_year_selected),
            'country'    =>array("label"=> $sbJson['responseObject']['country'],"value"=>'US' ),
            'state'    => array("label"=> $sbJson['responseObject']['state'],"value"=>'' ),
            'gateway_service_type' => $sbJson['responseObject']['gatewayServiceType']
        )
    );

    return $response;
};

$clientid=$_SESSION['SSMData']['clientGuid'];
$client_id=getClientId(ServicebusGetClientInfo($clientid));

$sbResponse = json_decode(ServicebusGetBillingInformation($clientid), TRUE);

 $json = return_new_json( $sbResponse );

echo json_encode($json);
